### ISSUE TITLE
Save some Flickr API request to retrieve sizes and urls

### ISSUE THREAD

**Issue by eboudrant** [PomepuyN/muzei-flickr#1]
Hi Nicolas,

You can save some request to Flickr API as you can get the size directly from the photo's request (flickr.photos.search) instead of calling flickr.photos.getSizes for each photo.

In flickr.photos.search add an extras parameter with the size you want : url_m, url_k, url_h...
ex: extras=url_m%2Curl_k%2Curl_h

All sizes are documented here : http://www.flickr.com/services/api/misc.urls.html

Thanks

**Comment by PomepuyN** [comment]
You're right. I missed these parameters. I will change it as soon as possible.

**Comment by PomepuyN** [comment]
I just took a look at this.
Actually, not all size can be returned by flickr.photos.search. Only the one listed here: http://www.flickr.com/services/api/flickr.photos.search.html

After having implementing it, the original size is always used, leading in massive data downloads. I strongly prefer one more call by photo than loading a bunch of data.

**Comment by eboudrant** [comment]
I can get all size available. See :

Request : 
http://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=bcb1e44260364b1bf6294f00a4cd1cb4&tags=tokyo&extras=owner_name%2Curl_m%2Curl_c%2Curl_b%2Curl_h%2Curl_k&format=json&nojsoncallback=1

Result :

``` json
{
    "id": "12704665293",
    "owner": "59114488@N00",
    "secret": "ddd5a487bf",
    "server": "7429",
    "farm": 8,
    "title": "Club Sega, Akihabara, Tokyo",
    "ispublic": 1,
    "isfriend": 0,
    "isfamily": 0,
    "ownername": "jev",
    "url_m": "http://farm8.staticflickr.com/7429/12704665293_ddd5a487bf.jpg",
    "height_m": "500",
    "width_m": "500",
    "url_c": "http://farm8.staticflickr.com/7429/12704665293_ddd5a487bf_c.jpg",
    "height_c": "800",
    "width_c": "800",
    "url_h": "http://farm8.staticflickr.com/7429/12704665293_6f12b120d7_h.jpg",
    "height_h": "1600",
    "width_h": "1600",
    "url_k": "http://farm8.staticflickr.com/7429/12704665293_78b9582109_k.jpg",
    "height_k": "2048",
    "width_k": "2048"
}
```

Note : Flickr photo's size doc is missing two sizes. They are the most interesting for you as they are the 2 biggest size : url_h (1600px) and url_k (2048px)

**Comment by PomepuyN** [comment]
I will take a look. I should have missed the right keys.
