### ISSUE TITLE
Search / User result issue

### ISSUE THREAD

**Issue by tunitowen** [PomepuyN/muzei-flickr#2]
Just noticed that if I search for something (example "street photography") it will do the search fine. However, the next photo will be that users photo not another search result.

**Comment by PomepuyN** [comment]
Let me understand. When you do a search, the first photo you get is related to the search but not the others?

**Comment by tunitowen** [comment]
Just tried to replicate the issue again and can't. If it appears again I will raise a new issue. Sorry.
